config/routes.rb
Rails.application.routes.draw do
  
  root 'intro#splash'
  
  post 'home/test' 
  get 'home/test'
  post 'home/test_ok' =>'home#test_ok'
  
  get 'session/new' =>'session#new'
  post 'session/create' =>'session#create'
  delete 'session/destroy' =>'session#destroy'
  
  get 'intro/splash' => 'intro#splash'
  get 'intro/explain' => 'intro#explain'

  get 'home/score' => 'home#score'
  get 'home/fail' => 'home#fail'
  
  get 'home/scenario1' => 'home#scenario1'
  get 'home/scenario2' => 'home#scenario2'
  get 'home/scenario3' => 'home#scenario3'
  get 'home/scenario3_2'
  get 'home/scenario4_1' => 'home#scenario4_1'
  get 'home/scenario4_2' => 'home#scenario4_2'
  get 'home/scenario4_3' => 'home#scenario4_3'
  get 'home/scenario5' => 'home#scenario5'
  get 'home/scenario6' => 'home#scenario6'
  
  get 'home/question1'
  get 'home/question2' => 'home#question2'
  get 'home/question3' => 'home#question3'
  get 'home/question3_2'
  get 'home/question4_1' => 'home#question4_1'
  get 'home/question4_2' => 'home#question4_2'
  get 'home/question4_3' => 'home#question4_3'
  get 'home/question5' => 'home#question5'
  get 'home/question6'
  
  get 'home/answer1'
  post 'home/answer1' => 'home#answer1'
  post 'home/answer2' => 'home#answer2'
  post 'home/answer3' => 'home#answer3'
  post 'home/answer3_2'
  post 'home/answer4_1'
  post 'home/answer4_2'
  post 'home/answer4_3'
  post 'home/answer5' => 'home#answer5'
  post 'home/answer6' => 'home#answer6'
  
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user, except: [:score]
  
  #test 
  def test_ok
    @test = params[:test_1]
    # num1 = params[:test_1]
    # result = num1
    # if (result == "1")
    #   render plain:"<script type='text/javascript'>alert('정답');</script>"
    #   # render(
    #   #   html: "<script>alert('Yes users!')</script>".html_safe,
    #   #   layout: 'application'
    #   # )
    # else
    #   render plain:"<script type='text/javascript'>alert('땡');</script>"
    #   # render(
    #   #   html: "<script>alert('No users!')</script>".html_safe,
    #   #   layout: 'application'
    #   # )
    # end
  end
  
  def test
    a_date = Time.new(2015, 8, 1, 14, 35, 0)
    b_date = Time.new(2015, 8, 1, 14, 37, 0)
    @test = ((b_date - a_date)).to_i
  end
  
  # 랭킹
  def score
    reset_session
    @scores = Score.order(clear: :asc)
  end
  def fail
    Score.create(
      major: session[:current_user_major],
      number: session[:current_user_number],
      name: session[:current_user_name]
    )
    redirect_to "/home/score"
  end
  
  # 시나리오
  def scenario1
  end
  def scenario2
  end
  def scenario3
  end
  def scenario4
  end
  def scenario5
  end
  def scenario6
  end
  def scenario7
  end
  def scenario8
  end
  def scenario9
  end
  def scenario10
  end
  
  # 문제
  def question1
    
  end
  def question2
  end
  def question3
  end
  def question3_1
  end
  def question3_2
  end
  def question4
  end
  def question5
  end
  def question6
  end
  def question7
  end
  def question8
  end
  def question9
  end
  def question10
  end
  
  # 정답
  def answer1
    num1 = params[:text1]
    num2 = params[:text2]
    num3 = params[:text3]
    num4 = params[:text4]
    question1 = Question.find(1)
    # question1 = "0000"
    result = num1 + num2 + num3 + num4
    
    # 여기서부터
    now_time = Time.new.in_time_zone("Asia/Seoul")
    session[:res] = 0
    if (result == question1.q_answer)
    # if (result==question1)
      session[:wrong] =""
      session[:answer]=0
      redirect_to "/home/scenario2"
    else
      session[:answer] += 1
      if (session[:answer]==1)
        session[:wrong] = "틀렸습니다!"
      elsif (session[:answer]==2)
        session[:answer] = 0
        session[:times] = Time.now.in_time_zone("Asia/Seoul").advance(seconds: 30).strftime("%B %d, %Y %H:%M:%S")
        session[:wrong] = ""
        session[:res] = 1
      end
      render :question1
    end
  end
  def answer2
    text1 = params[:text1]
    text2 = params[:text2]
    text3 = params[:text3]
    text4 = params[:text4]
    text5 = params[:text5]
    text6 = params[:text6]
    text7 = params[:text7]
    text8 = params[:text8]
    text9 = params[:text9]
    text10 = params[:text10]
    question2 = Question.find(2)
    result = text1+text2+text3+text4+text5+text6+text7+text8+text9+text10
    
    # 여기서부터
    now_time = Time.new.in_time_zone("Asia/Seoul")
    session[:res] = 0
    if (result == question2.q_answer)
    # if (result==question1)
      session[:wrong] =""
      session[:answer]=0
      redirect_to "/home/scenario3"
    else
      session[:answer] += 1
      if (session[:answer]==1)
        session[:wrong] = "틀렸습니다!"
      elsif (session[:answer]==2)
        session[:answer] = 0
        session[:times] = Time.now.in_time_zone("Asia/Seoul").advance(seconds: 30).strftime("%B %d, %Y %H:%M:%S")
        session[:wrong] = ""
        session[:res] = 1
      end
      render :question2
    end
  end
  
  def answer3
    result=params[:major]
    question3 = Question.find(3)
    # 여기서부터
    now_time = Time.new.in_time_zone("Asia/Seoul")
    session[:res] = 0
    if (result == question3.q_answer)
    # if (result==question1)
      session[:wrong] =""
      session[:answer]=0
      redirect_to "/home/scenario4_1"
    
    elsif (result == "emb")
      redirect_to "/home/scenario4_2"
    
    else
      session[:answer] += 1
      if (session[:answer]==1)
        session[:wrong] = "틀렸습니다!"
      elsif (session[:answer]==2)
        session[:answer] = 0
        session[:times] = Time.now.in_time_zone("Asia/Seoul").advance(seconds: 30).strftime("%B %d, %Y %H:%M:%S")
        session[:wrong] = ""
        session[:res] = 1
      end
      render :question3
    end
  end

  def answer3_2
    text1=params[:major]
    num1=params[:lock_2]
    num2=params[:lock_3]
    result=text1+num1+num2
    question3_2 = Question.find(4)
    # 여기서부터
    now_time = Time.new.in_time_zone("Asia/Seoul")
    session[:res] = 0
    if (result == question3_2.q_answer)
    # if (result==question1)
      session[:wrong] =""
      session[:answer]=0
      redirect_to "/home/scenario5"
    else
      session[:answer] += 1
      if (session[:answer]==1)
        session[:wrong] = "틀렸습니다!"
      elsif (session[:answer]==2)
        session[:answer] = 0
        session[:times] = Time.now.in_time_zone("Asia/Seoul").advance(seconds: 30).strftime("%B %d, %Y %H:%M:%S")
        session[:wrong] = ""
        session[:res] = 1
      end
      render :question3_2
    end
  end
  
  def answer4_1
    text1 = params[:text1]
    text2 = params[:text2]
    text3 = params[:text3]
    text4 = params[:text4]
    question4_1 = Question.find(5)
    result = text1+text2+text3+text4
    
    # 여기서부터
    now_time = Time.new.in_time_zone("Asia/Seoul")
    session[:res] = 0
    if (result == question4_1.q_answer)
    # if (result==question1)
      session[:wrong] =""
      session[:answer]=0
      redirect_to "/home/scenario5"
    else
      session[:answer] += 1
      if (session[:answer]==1)
        session[:wrong] = "틀렸습니다!"
      elsif (session[:answer]==2)
        session[:answer] = 0
        session[:times] = Time.now.in_time_zone("Asia/Seoul").advance(seconds: 30).strftime("%B %d, %Y %H:%M:%S")
        session[:wrong] = ""
        session[:res] = 1
      end
      render :question4_1
    end
  end
  def answer4_2
    num1 = params[:text1]
    num2 = params[:text2]
    num3 = params[:text3]
    question4_2 = Question.find(6)
    result = num1 + num2 + num3
    
    # 여기서부터

    now_time = Time.new.in_time_zone("Asia/Seoul")
    session[:res] = 0
    if (result == question4_2.q_answer)
    # if (result==question1)
      session[:wrong] =""
      session[:answer]=0
      redirect_to "/home/scenario4_3"
    else
      session[:answer] += 1
      if (session[:answer]==1)
        session[:wrong] = "틀렸습니다!"
      elsif (session[:answer]==2)
        session[:answer] = 0
        session[:times] = Time.now.in_time_zone("Asia/Seoul").advance(seconds: 30).strftime("%B %d, %Y %H:%M:%S")
        session[:wrong] = ""
        session[:res] = 1
      end
      render :question4_2
    end
  end
  
  def answer4_3
    result=params[:text1]
    question4_3 = Question.find(7)
  
    # 여기서부터
    now_time = Time.new.in_time_zone("Asia/Seoul")
    session[:res] = 0
    if (result == question4_3.q_answer)
    # if (result==question1)
      session[:wrong] =""
      session[:answer]=0
      redirect_to "/home/scenario3_2"
    else
      session[:answer] += 1
      if (session[:answer]==1)
        session[:wrong] = "틀렸습니다!"
      elsif (session[:answer]==2)
        session[:answer] = 0
        session[:times] = Time.now.in_time_zone("Asia/Seoul").advance(seconds: 30).strftime("%B %d, %Y %H:%M:%S")
        session[:wrong] = ""
        session[:res] = 1
      end
      render :question4_3
    end
  end
  def answer5
    text1 = params[:text1]
    text2 = params[:text2]
    text3 = params[:text3]
    question5 = Question.find(8)
    result = text1+text2+text3
    
    # 여기서부터
    now_time = Time.new.in_time_zone("Asia/Seoul")
    session[:res] = 0
    if (result == question5.q_answer)
    # if (result==question1)
      session[:wrong] =""
      session[:answer]=0
      redirect_to "/home/scenario6"
    else
      session[:answer] += 1
      if (session[:answer]==1)
        session[:wrong] = "틀렸습니다!"
      elsif (session[:answer]==2)
        session[:answer] = 0
        session[:times] = Time.now.in_time_zone("Asia/Seoul").advance(seconds: 30).strftime("%B %d, %Y %H:%M:%S")
        session[:wrong] = ""
        session[:res] = 1
      end
      render :question5
    end
  end
  
  def answer6
    result= params[:text1]
    question6 = Question.find(9)
    
    # 여기서부터
    check_answer
    now_time = Time.new.in_time_zone("Asia/Seoul")
    session[:res] = 0
    if (result == question6.q_answer)
    # if (result==question1)
      session[:wrong] =""
      session[:answer]=0
      Score.create(
        major: session[:current_user_major],
        number: session[:current_user_number],
        name: session[:current_user_name],
        clear: @clear,
        clear_m: @clear_m,
        clear_s: @clear_s
      )
      redirect_to "/home/score"
    else
      session[:answer] += 1
      if (session[:answer]==1)
        session[:wrong] = "틀렸습니다!"
      elsif (session[:answer]==2)
        session[:answer] = 0
        session[:times] = Time.now.in_time_zone("Asia/Seoul").advance(seconds: 30).strftime("%B %d, %Y %H:%M:%S")
        session[:wrong] = ""
        session[:res] = 1
      end
      render :question6
    end
  end
  
  public
  def set_user
    if (session[:current_user_number].nil?)
      redirect_to '/session/new'
    else
      set_time
      @user_name = session[:current_user_name]
    end
  end
  def set_time
    user = User.find_by(user_number: session[:current_user_number])
    @time = user.created_at.in_time_zone("Asia/Seoul").strftime("%B %d, %Y %H:%M:%S")
  end
  def check_answer
    user = User.find_by(user_number: session[:current_user_number])
    starttime = user.created_at.in_time_zone("Asia/Seoul")
    cleartime = Time.now.in_time_zone("Asia/Seoul")
    
    @clear = (cleartime-starttime).to_i
    @clear_m = ((cleartime-starttime)/60).to_i
    @clear_s = ((cleartime-starttime)%60).to_i
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<div class="header">
  <div id="header_logo">
    Save INU <%= link_to "삭제", session_destroy_path, method: 'delete' %>
  </div>
  <div id="ViewTimer"></div>
</div>

app/views/home/question1.html.erb
<%= render 'header' %>
<div class="wrap_home">
  <div class="inform">
      <strong>032)</br></br> -</strong>
  </div>
  <form action="/home/answer1" name="inputform" id="frm" method = 'post'>
      <div class= writeAnswer>
        <div class="col">
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text1" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
            
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text2" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
            
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text3" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
            
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text4" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
        </div>
    </div>
    <input type="submit" class="btn btn-primary" value="제출" id="chb" >
  </form>
  <div class="timer"><%=@time%></div>
  <div id="yes"><%=session[:wrong]%></div>
  
</div>

app/views/home/question2.html.erb
<%= render 'header' %>
<div class="wrap_home">
  <div class="inform">
      <img src="/assets/q02.png" width="300px"></img>
      <p><strong>세 글자 단어는 가나다 순서로</strong></p>
    </div>
  <form action="/home/answer2" method="post" name="inputform">
    
      <div class= writeAnswer>
          
      <div class= "cols">
        <div class="lock">
          <input type="text" class="str" name="text1" maxlength="1"></input>
          <input type="text" class="str" name="text2" maxlength="1"></input>
          <input type="text" class="str" name="text3" maxlength="1"></input>
          <input type="text" class="str" name="text4" maxlength="1" style="border-color: #ff0000;"></input>
        </div>
      </div>
      
       <div class= "cols">
        <div class="lock">
          <input type="text" class="str" name="text5" maxlength="1" style="border-color: #ff0000;"></input>
          <input type="text" class="str" name="text6" maxlength="1"></input>
          <input type="text" class="str" name="text7" maxlength="1"></input>
        </div>
      </div>
      
       <div class= "cols">
        <div class="lock">
          <input type="text" class="str" name="text8" maxlength="1"></input>
          <input type="text" class="str" name="text9" maxlength="1" style="border-color: #ff0000;"></input>
          <input type="text" class="str" name="text10" maxlength="1"></input>
        </div>
      </div>
      
    </div>
    <button type="submit" class="btn btn-primary" >다음</button>
  </form>
  <div class="timer"><%=@time%></div>
  <div id="yes"><%=session[:wrong]%></div>
</div>

<script>
  function autotab(current,to){
    if (current.getAttribute && 
      current.value.length==current.getAttribute("maxlength")) {
        to.focus() 
    }
  }
</script>

app/views/home/question3.html.erb
<%= render 'header' %>
<div class="wrap_home">
  <div class="inform">가야할 곳은 어디지?</div>
  <form action="/home/answer3" method="post">
    <div class="col">
    <div class="cols ra">
      <div class="custom-control custom-radio">
        <input type="radio" id="customRadio1" name="major" class="custom-control-input" value="com">
        <label class="custom-control-label" for="customRadio1">컴퓨터공학부</label>
      </div>
      <div class="custom-control custom-radio">
        <input type="radio" id="customRadio2" name="major" class="custom-control-input" value="iac">
        <label class="custom-control-label" for="customRadio2">정보통신공학과</label>
      </div>
      <div class="custom-control custom-radio">
        <input type="radio" id="customRadio3" name="major" class="custom-control-input" value="emb">
        <label class="custom-control-label" for="customRadio3">임베디드시스템공학과</label>
      </div>

    
    </div>
    </div>
    <button type="submit" class="btn btn-primary" >다음</button>
  </form>
  <div class="timer"><%=@time%></div>
  <div id="yes"><%=session[:wrong]%></div>
</div>

app/views/home/question3_2.html.erb
<%= render 'header' %>

<div class="wrap_home">
  <div class="inform">
      <p><strong>이제 정말 가야할 곳을 찾아줘!</strong></p>
      <p><strong>그리고 다른 창문에서 찾은 네 번째 숫자도 입력하자.</strong></p>
  </div>
  <form action="/home/answer3_2" name="inputform" id="frm" method="POST">
      <div class= writeAnswer>
        <div class="col">
          <div class="cols ra">
            <div class="custom-control custom-radio">
              <input type="radio" id="customRadio1" name="major" class="custom-control-input" value="com">
              <label class="custom-control-label" for="customRadio1">컴퓨터공학부</label>
            </div>
            <div class="custom-control custom-radio">
              <input type="radio" id="customRadio2" name="major" class="custom-control-input" value="iac">
              <label class="custom-control-label" for="customRadio2">정보통신학과</label>
            </div>
            <div class="custom-control custom-radio">
              <input type="radio" id="customRadio3" name="major" class="custom-control-input" value="emb">
              <label class="custom-control-label" for="customRadio3">임베디드시스템공학과</label>
            </div>
          </div>
        </div>
        
        <div class="col">
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="lock_2" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
              
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="lock_3" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
        </div>
    </div>
    <input type="submit" class="btn btn-primary" value="제출" id="chb">
  </form>
  <div class="timer"><%=@time%></div>
  <div id="yes"><%=session[:wrong]%></div>
</div>

app/views/home/question4_2.html.erb
<%= render 'header' %>
<div class="wrap_home">
  <div class="inform">
      <strong>임베디드공학과 사무실의 호실은?</strong>
  </div>
  <form action="/home/answer4_2" name="inputform" id="frm" method = 'post'>
      <div class= writeAnswer>
        <div class="col">
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text1" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
            
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text2" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
            
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text3" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>

        </div>
    </div>
    <input type="submit" class="btn btn-primary" value="제출" id="chb" >
  </form>
  <div class="timer"><%=@time%></div>
  <div id="yes"><%=session[:wrong]%></div>
  
</div>

app/views/home/question5.html.erb
<%= render 'header' %>

<div class="wrap_home">
  <div class="inform">
      <strong>[자물쇠 풀기]<br><img src="/assets/q05.png" width="300px"><br>사물함 자물쇠를 풀고 그 안을 확인하자.<br><br>[사물함 속 편지]<br>어디로 가야하지?</strong>
  </div>
  <form action="/home/answer5" name="inputform" id="frm" method="POST">
      <div class= writeAnswer>
        <div class="col">
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text1" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
            
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text2" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
            
          <div class="lock">
            <div class = "bt_up">▲</div>
            <input type = "text" name ="text3" class="num" value="0" readonly></input>
            <div class = "bt_down">▼</div>
          </div>
            
        </div>
    </div>
    <input type="submit" class="btn btn-primary" value="제출" id="chb" >
  </form>
  <div class="timer"><%=@time%></div>
  <div id="yes"><%=session[:wrong]%></div>
</div>

app/views/home/question6.html.erb
<%= render 'header' %>
<div class="wrap_home">
  <form action="/home/answer6" method="post" name="inputform">
    <div class="inform">
      <p><strong>바이러스 해제코드를 입력해주십시오</strong></p>
    </div>
      <div class= writeAnswer>
          
      <div class= "cols">
        <div class="lock">
          <input type="text" class="long" name="text1"></input>
        </div>
      </div>
      
       
      <button type="submit" class="btn btn-primary" >다음</button>
    </div>
  </form>
  <div class="timer"><%=@time%></div>
  <div id="yes"><%=session[:wrong]%></div>
</div>

<script>
  function autotab(current,to){
    if (current.getAttribute && 
      current.value.length==current.getAttribute("maxlength")) {
        to.focus() 
    }
  }
</script>

app/views/home/scenario2.html.erb
<%= render 'header' %>

<div class="wrap_home">
  <div class="wrap_scene">
    <div class="scene2">
      <a class="btn btn-primary" href="/home/question2" role="button">다음</a>
    </div>
  </div>
  <div class="timer"><%=@time%></div>
</div>

app/views/home/scenario3.html.erb
<%= render 'header' %>

<div class="wrap_scene">
  <div class="scene3">
    <a class="btn btn-primary" href="/home/question3" role="button">다음</a>
  </div>
  <div class="timer"><%=@time%></div>
</div>

app/views/home/scenario4_2.html.erb
<%= render 'header' %>

<div class="wrap_scene">
  <div class="scene4_2">
    <img src=""></img>
    <p><strong></strong></p>
    <a class="btn btn-primary" href="/home/question4_2" role="button">다음</a>
  </div>
  <div class="timer"><%=@time%></div>
</div>

app/views/home/scenario5.html.erb
<%= render 'header' %>

<div class="wrap_scene">
  <div class="scene5">
    <p></p>
    <a class="btn btn-primary" href="/home/question5" role="button">다음</a>
  </div>
  <div class="timer"><%=@time%></div>
</div>

app/views/home/test.html.erb
<form action = '/home/test' method = 'post'>
  <div class = "bt_up">▲</div>
  <input type = "text" name ="test_1" class="num" value="0" readonly></input>
  <div class = "bt_down">▼</div>

  <button type="submit">▼</button>
</form>

<%=@testtime%>분
<%=@testtwo%>초

<div class="ans" style="display:none;"><%=@test%></div>

<script>
  function button1_click() {
	var ans = $('.ans').text();
	var you = <%=@test%>
	alert(you);
	if (ans == you) {
	  alert("정답");
	}
	else {
	  alert("꺼져 " + you);
	}
}
</script>

app/views/home/test_ok.html.erb
<%= @test %>